Repository Chris1320/BU_Student_Information_System, pull requests merged in 2024-10, with the labels that each got.

#8 Withsheet2
  StudentInformationSheet/StudentInformationSheet/StudentInformationSheet.csproj
  StudentInformationSheet/StudentInformationSheet/StudentSheetPage2.Designer.cs
  StudentInformationSheet/StudentInformationSheet/StudentSheetPage2.cs
  StudentInformationSheet/StudentInformationSheet/StudentSheetPage2.resx
Labels: enhancement

#11 Added public variables and method on Student Model and User Model
  StudentInformationSheet/StudentInformationSheet/Models/StudentModel.cs
  StudentInformationSheet/StudentInformationSheet/Models/UserModel.cs
Labels: enhancement

#14 feat: go to designated panel depending on user privilege
  StudentInformationSheet/StudentInformationSheet/Models/UserModel.cs
  StudentInformationSheet/StudentInformationSheet/Views/LoginPage.cs
Labels: enhancement

#12 updated forms & added realtaiizor package
  Server/db_schema.sql
  StudentInformationSheet/StudentInformationSheet/User.cs
Labels: enhancement

#17 ci: create `dotnet.yml`
  .github/workflows/artifact.yml
  .github/workflows/dotnet.yml
  .github/workflows/super-linter.yml
Labels: enhancement, good first issue

#16 Modified the StudentModel according to UserModel
  StudentInformationSheet/StudentInformationSheet/Models/StudentModel.cs
Labels: enhancement

#36 Update Design
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet.sln
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/App.config
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet.csproj
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Handlers/DatabaseHandler.cs
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Handlers/ImageHandler.cs
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Handlers/PasswordHandler.cs
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Models/StudentModel.cs
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Models/UserModel.cs
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Program.cs
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Properties/AssemblyInfo.cs
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Properties/Resources.Designer.cs
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Properties/Resources.resx
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Properties/Settings.Designer.cs
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Properties/Settings.settings
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Resources/add.png
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Resources/admin-profile.png
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Resources/background.png
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Resources/bu-cite.png
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Resources/default-profile.png
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Resources/delete.png
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Resources/line-textbox.png
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Resources/password.png
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Resources/print.png
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Resources/update.png
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Resources/user.png
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Resources/white-opacity.png
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Settings.cs
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Tools/Dashboard.Designer.cs
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Tools/Dashboard.cs
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Tools/Dashboard.resx
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Tools/ManageUsers.Designer.cs
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Tools/ManageUsers.cs
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Tools/ManageUsers.resx
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Tools/ProfileAdmin.Designer.cs
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Tools/ProfileAdmin.cs
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Tools/ProfileAdmin.resx
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Tools/ProfileSuperAdmin.Designer.cs
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Tools/ProfileSuperAdmin.cs
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Tools/ProfileSuperAdmin.resx
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Views/AdminDashboard.Designer.cs
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Views/AdminDashboard.cs
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Views/AdminDashboard.resx
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Views/LoginPage.Designer.cs
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Views/LoginPage.cs
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Views/LoginPage.resx
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Views/StudentSheet.Designer.cs
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Views/StudentSheet.cs
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Views/StudentSheet.resx
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Views/SuperAdminDashboard.Designer.cs
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Views/SuperAdminDashboard.cs
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Views/SuperAdminDashboard.resx
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/packages.config
Labels: enhancement

#37 V0.1.0
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/App.config
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet.csproj
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Handlers/DatabaseHandler.cs
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Models/StudentModel.cs
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Models/StudentSubModels/GuardianAngel.cs
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Models/StudentSubModels/StudentAcademicHistory.cs
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Models/StudentSubModels/StudentAddressInformation.cs
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Models/StudentSubModels/StudentContactInformation.cs
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Models/StudentSubModels/StudentFamilyInformation.cs
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Models/StudentSubModels/StudentName.cs
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Models/StudentSubModels/StudentPersonalInformation.cs
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Models/StudentSubModels/StudentPersonality.cs
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Models/UserModel.cs
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Tools/ManageUsers.Designer.cs
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Tools/ManageUsers.cs
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Tools/ProfileSuperAdmin.Designer.cs
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Tools/ProfileSuperAdmin.cs
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Views/AdminDashboard.cs
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Views/LoginPage.Designer.cs
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Views/LoginPage.cs
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Views/LoginPage.resx
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Views/SuperAdminDashboard.cs
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/packages.config
  Server/db_schema.sql
  StudentInformationSheet/StudentInformationSheet/Handlers/DatabaseHandler.cs
  StudentInformationSheet/StudentInformationSheet/Handlers/ImageHandler.cs
  StudentInformationSheet/StudentInformationSheet/Models/UserModel.cs
  StudentInformationSheet/StudentInformationSheet/StudentInformationSheet.csproj
  StudentInformationSheet/StudentInformationSheet/Views/AddUserAccPage.Designer.cs
  StudentInformationSheet/StudentInformationSheet/Views/AddUserAccPage.cs
  StudentInformationSheet/StudentInformationSheet/Views/AddUserAccPage.resx
  StudentInformationSheet/StudentInformationSheet/Views/AdminMenu.cs
  StudentInformationSheet/StudentInformationSheet/Views/LoginPage.Designer.cs
  StudentInformationSheet/StudentInformationSheet/Views/LoginPage.cs
  StudentInformationSheet/StudentInformationSheet/Views/LoginPage.resx
Labels: enhancement, help wanted

#38 Update Design (2)
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/App.config
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet.csproj
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Properties/Resources.Designer.cs
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Properties/Resources.resx
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Properties/Settings.Designer.cs
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Resources/admin-img.png
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Tools/Dashboard.Designer.cs
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Tools/Dashboard.resx
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Tools/ManageUsers.Designer.cs
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Tools/ProfileAdmin.Designer.cs
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Tools/ProfileSuperAdmin.Designer.cs
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Views/AdminDashboard.Designer.cs
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Views/AdminDashboard.resx
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Views/LoginPage.Designer.cs
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Views/LoginPage.resx
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Views/StudentSheet.Designer.cs
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Views/StudentSheet.resx
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Views/SuperAdminDashboard.Designer.cs
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Views/SuperAdminDashboard.resx
Labels: enhancement

#42 StudentSheet form: add textboxes
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet.csproj
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Properties/Resources.Designer.cs
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Properties/Resources.resx
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Resources/delete (1).png
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Resources/save.png
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Resources/save1.png
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Tools/Dashboard.cs
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Tools/Dashboard.resx
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Tools/ManageUsers.cs
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Views/StudentSheet.Designer.cs
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Views/StudentSheet.cs
  BaliuagU_StudentInformationSheet/BaliuagU_StudentInformationSheet/Views/StudentSheet.resx
Labels: enhancement
